version: '3'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/myapp
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: alfred.localhost
      VIRTUAL_PORT: 3001
    expose:
      - 3001
networks:
  default:
    external:
      name: nginx-proxy
